### ISSUE TITLE
REDIS1 error 

### ISSUE THREAD

**Issue by xalekx** [gojek/feast#193]
Error:
debug_error_string = "{"created":"@1557752707.241967824","description":"Error received from peer ipv4:127.0.0.1:6565","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Validation for feature spec with id ride.month failed: Serving store with id REDIS1 does not exist","grpc_status":11}"

How to register a REDIS1 storage to the core ?

- Version:16.04
- Platform:Ubuntu
- Subsystem:

**Comment by tims** [comment]
Hi @xalekx the storage is configured on the helm chart. 

eg in your values.yaml

you might have:
```
store:
  errors:
    type: "stdout"
  warehouse:
    type: "bigquery"
    options: '{"project": "gcp-project-id", "dataset": "feast"}'
  serving:
    type: "redis"
    options: '{"host": "...", "port": "6379"}'
```

We used to have a function where a Feature could choose it's own stores, and we removed this.
How old is the version you are trying out?
