### ISSUE TITLE
Python unit tests fail with new proto files

### ISSUE THREAD

**Issue by Yanson** [gojek/feast#448]
In our CI pipeline, we regenerate all sources rather than relying on committed files. This is causing master build failures since this commit: https://github.com/gojek/feast/pull/438

## Expected Behavior 

Build and tests pass

## Current Behavior

Unit test python fails

## Steps to reproduce

1. Re-generate python files with `cd protos; make gen-python`
1. Run unit tests with `cd sdk/python; pip install -r requirements-ci.txt && pip install -e . && pytest --junitxml=python-sdk-test-report.xml`

### Specifications

latest master

## Possible Solution

Add required dependencies to requirements. tensorflow_metadata?

**Comment by Yanson** [comment]
Build log from Cloud Build step:
```yaml
- id: gen-proto-python
  waitFor: ['-']
  name: 'gcr.io/my-org/protoc-python'
  dir: '/workspace/protos'
  entrypoint: make
  args: ['gen-python']
- id: unit-test-python-sdk
  waitFor: ['gen-proto-python']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  entrypoint: sh
  args: ['-c', 'pip install -r requirements-ci.txt && pip install -e . && pytest --junitxml=/log/python-sdk-test-report.xml']
```

[unit-test-python-sdk.txt](https://github.com/gojek/feast/files/4123830/unit-test-python-sdk.txt)

Excerpt:
```
ImportError while importing test module '/workspace/sdk/python/tests/test_client.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_client.py:23: in <module>
    import feast.core.CoreService_pb2_grpc as Core
feast/__init__.py:9: in <module>
    from .client import Client
feast/client.py:32: in <module>
    from feast.core.CoreService_pb2 import (
feast/core/CoreService_pb2.py:16: in <module>
    from feast.core import FeatureSet_pb2 as feast_dot_core_dot_FeatureSet__pb2
feast/core/FeatureSet_pb2.py:21: in <module>
    from tensorflow_metadata.proto.v0 import schema_pb2 as tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2
E   ModuleNotFoundError: No module named 'tensorflow_metadata'
```
